// Code generated by goyacc parserPro.y. DO NOT EDIT.

//line parserPro.y:2

package Grammar

import __yyfmt__ "fmt"

//line parserPro.y:3

import (
	"ProyectoArchivos/comandos"
	"bufio"
	"bytes"
	"fmt"
	"os"
	"strings"
)

//line parserPro.y:17
type yySymType struct {
	yys int
	cad string
}

const T_ID = 57346
const T_NUMERO = 57347
const T_LETRA = 57348
const T_EXEC = 57349
const T_PATH = 57350
const T_ARROW = 57351
const T_ROUTE = 57352
const T_PAUSE = 57353
const T_MKDISK = 57354
const T_SIZE = 57355
const T_NAME = 57356
const T_UNIT = 57357
const T_RMDISK = 57358
const T_FDISK = 57359
const T_TYPE = 57360
const T_FIT = 57361
const T_DELETE = 57362
const T_ADD = 57363
const T_ARC_DKS = 57364

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"T_ID",
	"T_NUMERO",
	"T_LETRA",
	"T_EXEC",
	"T_PATH",
	"T_ARROW",
	"T_ROUTE",
	"T_PAUSE",
	"T_MKDISK",
	"T_SIZE",
	"T_NAME",
	"T_UNIT",
	"T_RMDISK",
	"T_FDISK",
	"T_TYPE",
	"T_FIT",
	"T_DELETE",
	"T_ADD",
	"T_ARC_DKS",
	"'-'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parserPro.y:57

func ScannearEntrada() {
	reader := bufio.NewReader(os.Stdin)
	yyDebug = 0
	var text string
	var textMult string
	var err error
	for {
		text, err = reader.ReadString('\n')
		if err != nil {
			fmt.Println("Ha ocurrido un error")
		} else { //Leemos el input
			text = strings.TrimSpace(text)
			if verificarMultilinea(text) { //Recolectamos la multilinea
				text = text[0 : len(text)-2]
				for {
					fmt.Println("...")
					textMult, err = reader.ReadString('\n')
					if err != nil {
						fmt.Println("Ha ocurrido un error")
					} else {
						text += textMult
						text = strings.TrimSpace(text)
					}
					if !verificarMultilinea(text) {
						break
					} else {
						text = text[0 : len(text)-2]
					}
				}
			}
			fmt.Println("-->", text)
			l := parseoCompleto(bytes.NewBufferString(text), "file.name")
			yyParse(l)
		}
	}
}

func verificarMultilinea(cadena string) bool {
	longitud := len(cadena)
	if cadena[longitud-2] == '\\' && cadena[longitud-1] == '*' {
		return true
	}
	return false
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 37

var yyAct = [...]int{
	15, 10, 11, 7, 36, 13, 35, 14, 33, 32,
	16, 17, 18, 19, 2, 31, 37, 30, 3, 4,
	23, 9, 29, 5, 6, 22, 24, 25, 28, 26,
	21, 20, 27, 34, 12, 8, 1,
}

var yyPact = [...]int{
	7, -1000, -20, -1000, -22, -21, -8, 23, -22, -1000,
	12, 21, -1000, 26, -1000, -1000, -1000, -1000, -1000, -1000,
	19, -1000, 13, 8, 6, 0, -1000, -1000, -2, 28,
	-4, -18, 10, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int{
	0, 36, 35, 21, 34,
}

var yyR1 = [...]int{
	0, 1, 1, 1, 1, 1, 2, 2, 3, 3,
	3, 3, 4, 4, 4, 4, 4, 4, 4,
}

var yyR2 = [...]int{
	0, 5, 1, 2, 3, 2, 2, 1, 4, 4,
	4, 4, 2, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int{
	-1000, -1, 7, 11, 12, 16, 17, 23, -2, -3,
	23, 23, -4, 13, 15, 8, 18, 19, 20, 21,
	8, -3, 13, 8, 14, 15, 8, 6, 9, 9,
	9, 9, 9, 10, 5, 10, 22, 6,
}

var yyDef = [...]int{
	0, -2, 0, 2, 0, 0, 0, 0, 3, 7,
	0, 0, 5, 0, 13, 14, 15, 16, 17, 18,
	0, 6, 0, 0, 0, 0, 4, 12, 0, 0,
	0, 0, 0, 1, 8, 9, 10, 11,
}

var yyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 23,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parserPro.y:31
		{
			fmt.Println("Comando EXEC")
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parserPro.y:32
		{
			fmt.Println("Comando PAUSE")
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parserPro.y:33
		{
			fmt.Println("Comando MKDISK")
			comandos.CrearArchivo(comandos.TamanioSint, comandos.RutaSint, comandos.NameSint, comandos.DimenSin)
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parserPro.y:34
		{
			fmt.Println("Comando RMDISK")
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parserPro.y:35
		{
			fmt.Println("Comando FDISK")
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parserPro.y:38
		{
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parserPro.y:39
		{
		}
	case 8:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parserPro.y:42
		{
			comandos.TamanioSint = yyDollar[4].cad
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parserPro.y:43
		{
			comandos.RutaSint = yyDollar[4].cad
		}
	case 10:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parserPro.y:44
		{
			comandos.NameSint = yyDollar[4].cad
		}
	case 11:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parserPro.y:45
		{
			comandos.DimenSin = yyDollar[4].cad
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parserPro.y:48
		{
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parserPro.y:49
		{
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parserPro.y:50
		{
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parserPro.y:51
		{
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parserPro.y:52
		{
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parserPro.y:53
		{
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parserPro.y:54
		{
		}
	}
	goto yystack /* stack new state and value */
}
